// Generated by https://quicktype.io

export interface Device {
  player:           boolean;
  id:               string;
  offSet:           string;
  serialNumber:     string;
  playerName:       string;
  verificationCode: string;
  userID:           string;
  teamID:           string;
  hided:            boolean;
  playerID:         boolean;
}
