// Generated by https://quicktype.io

export interface Group {
  teamName:          string;
  lowerCaseTeamName: string;
  hided:             boolean;
  id:                string;
  userID:            string;
  logoUrl:           string;
  gmt:               string;
  deleted:           boolean;
}
