// Generated by https://quicktype.io

export interface Player {
  birthplace: Birthplace;
  pictureUrl: string;
  deviceSN:   boolean;
  sex:        string;
  device:     boolean;
  userID:     string;
  birthdate:  Birthdate;
  teamID:     string;
  lastName:   string;
  teamLogo:   string;
  sport:      string;
  id:         string;
  name:       string;
  hided:      boolean;
  deviceID:   boolean;
}

export interface Birthdate {
  seconds:     number;
  nanoseconds: number;
}

export interface Birthplace {
  alpha3Code:  string;
  name:        string;
  numericCode: string;
  alpha2Code:  string;
  callingCode: string;
}
