// Generated by https://quicktype.io

export interface User {
  id:            string;
  role:          string;
  nickName:      string;
  email:         string;
  UID:           string;
  uid:           string;
  collaborators: any[];
  deleted:       boolean;
}
